services:
  - type: web
    name: notes-api
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: notes-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: notes-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: notes-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: notes-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: notes-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000

databases:
  - name: notes-db
    plan: free
    databaseName: notes
    user: notes_user
