services:
  - type: web
    name: notes-api
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: notes-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: notes-db
          property: password
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000

databases:
  - name: notes-db
    plan: free
    databaseName: notes
    user: notes_user
